
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LLAVE_ABRE = 19;
  public static final int ELSE = 10;
  public static final int LLAVE_CIERRA = 20;
  public static final int INT = 4;
  public static final int WHILE = 11;
  public static final int OPERADOR_MULTIPLICACION = 16;
  public static final int OPERADOR_ASIGNACION = 14;
  public static final int PARENTESIS_ABRE = 17;
  public static final int RETURN = 8;
  public static final int PARENTESIS_CIERRA = 18;
  public static final int TRUE = 12;
  public static final int IF = 9;
  public static final int OPERADOR_SUMA = 15;
  public static final int EOF = 0;
  public static final int MAIN = 7;
  public static final int FALSE = 13;
  public static final int error = 1;
  public static final int NUMERO = 3;
  public static final int IDENTIFICADOR = 2;
  public static final int PUNTO_COMA = 21;
  public static final int BOOL = 5;
  public static final int VOID = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "NUMERO",
  "INT",
  "BOOL",
  "VOID",
  "MAIN",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "TRUE",
  "FALSE",
  "OPERADOR_ASIGNACION",
  "OPERADOR_SUMA",
  "OPERADOR_MULTIPLICACION",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "PUNTO_COMA"
  };
}

